### ISSUE TITLE
can this project avaliable for cdh 5.11 ?

### ISSUE THREAD

**Issue by zhaochl** [cloudera-labs/phoenix#4]
is it out of date for cdh 5.11+ ,or the project is abandoned

**Comment by fpompermaier** [comment]
Any interest with updating this?

**Comment by kverhoeven** [comment]
I could really use this package for CDH 5.11, but more important I'd like to see this on CDH 5.13. We use Phoenix, but without regular updates to Phoenix we can't update CDH.

**Comment by fpompermaier** [comment]
We use the official 4.7 parcel but it's getting quite old right now..

**Comment by zhaochl** [comment]
I have strong interest to updae this,but how to do that?

**Comment by fpompermaier** [comment]
The big problem here is whether Cloudera will ever continue to suppport an
alternative to Kudu.. :)

**Comment by chinogitano** [comment]
Just uploaded my best-effort PR.  Gurus and peers please feel free to review and comment.  It works for our CDH 5.12.1 environment.

**Comment by chinogitano** [comment]
Hi Flavio:

Yes, that was me on that thread as well ... ;-)
Looking forward to it.  Hope this contribution helps.

**Comment by chinogitano** [comment]
Flavio:

Also, can you explain a bit the relationship between the cloudera-labs/phoenix repo and the [Apache project base repo](https://github.com/apache/phoenix)?  All the work under [Phoenix Jiras](https://issues.apache.org/jira/browse/PHOENIX-2834?jql=project%20%3D%20PHOENIX%20AND%20text%20~%20CDH%20ORDER%20BY%20updated%20DESC) are done in the latter, even though a good part (and many topical branches) are CDH-specific.  For example, which Apache branch is cloudera-labs/phoenix [cdh5-4.3.0_1.0.0](https://github.com/cloudera-labs/phoenix/tree/cdh5-4.3.0_1.0.0) based on?  And is [phoenix1-4.7.0_1.3.0](https://github.com/cloudera-labs/phoenix/tree/phoenix1-4.7.0_1.3.0) (what I assume is the source for the CLAB_PHOENIX 1.3.0 parcel) based off [Apache 4.7.0-HBase-1.1](https://github.com/apache/phoenix/tree/4.7.0-HBase-1.1)?

**Comment by fpompermaier** [comment]
I assume that  cloudera-labs/phoenix repo is maintained by Cloudera that
(IMHO) doesn't have much interest into Phoenix integration (in favor of
Kudu), while Apache repo is supported by the community and is very
interested in any kind of contribution.
Since more and more users are not receiving any feedback from Cloudera they
started asking for CDH-related tickets on Phoenix JIRA (obtaining some
support).
Unfortunately this is not the ideal situation but I think that, in the end,
it will not be a big problem to support multiple release of Apache Phoenix
(the "vanilla" one and the Phoenix one) directly in the Apache repo

Best,
Flavio
